In [1]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.8.4
aiosignal                        1.3.1
alabaster                        0.7.13
albumentations                   1.2.1
altair                           4.2.2
anyio                            3.7.1
appdirs                          1.4.4
argon2-cffi                      21.3.0
argon2-cffi-bindings             21.2.0
array-record                     0.4.0
arviz                            0.15.1
astropy                          5.2.2
astunparse                       1.6.3
async-timeout                    4.0.2
attrs                            23.1.0
audioread                        3.0.0
autograd                         1.6.2
Babel                            2.12.1
backcall                         0.2.0
beautifulsoup4                   4.11.2
bleach                           6.0.0
blis                             0.7.9
blosc2                           2.0.0
bokeh                            2.4.3
branca                           0.6.0
build                            0.10.0
CacheControl                     0.13.1
cachetools                       5.3.1
catalogue                        2.0.8
certifi                          2023.5.7
cffi                             1.15.1
chardet                          4.0.0
charset-normalizer               2.0.12
chex                             0.1.7
click                            8.1.4
click-plugins                    1.1.1
cligj                            0.7.2
cloudpickle                      2.2.1
cmake                            3.25.2
cmdstanpy                        1.1.0
colorcet                         3.0.1
colorlover                       0.3.0
community                        1.0.0b1
confection                       0.1.0
cons                             0.4.6
contextlib2                      21.6.0
contourpy                        1.1.0
convertdate                      2.4.0
cufflinks                        0.17.3
cupy-cuda11x                     11.0.0
cvxopt                           1.3.1
cvxpy                            1.3.2
cycler                           0.11.0
cymem                            2.0.7
Cython                           0.29.36
dask                             2022.12.1
datascience                      0.17.6
db-dtypes                        1.1.1
dbus-python                      1.2.16
debugpy                          1.6.6
decorator                        4.4.2
defusedxml                       0.7.1
distributed                      2022.12.1
dlib                             19.24.2
dm-tree                          0.1.8
docutils                         0.16
dopamine-rl                      4.0.6
duckdb                           0.8.1
earthengine-api                  0.1.358
easydict                         1.10
ecos                             2.0.12
editdistance                     0.6.2
en-core-web-sm                   3.5.0
entrypoints                      0.4
ephem                            4.1.4
et-xmlfile                       1.1.0
etils                            1.3.0
etuples                          0.3.9
exceptiongroup                   1.1.2
fastai                           2.7.12
fastcore                         1.5.29
fastdownload                     0.0.7
fastjsonschema                   2.17.1
fastprogress                     1.0.3
fastrlock                        0.8.1
filelock                         3.12.2
Fiona                            1.9.4.post1
firebase-admin                   5.3.0
Flask                            2.2.5
flatbuffers                      23.5.26
flax                             0.7.0
folium                           0.14.0
fonttools                        4.40.0
frozendict                       2.3.8
frozenlist                       1.3.3
fsspec                           2023.6.0
future                           0.18.3
gast                             0.4.0
gcsfs                            2023.6.0
GDAL                             3.3.2
gdown                            4.6.6
gensim                           4.3.1
geographiclib                    2.0
geopandas                        0.13.2
geopy                            2.3.0
gin-config                       0.5.0
glob2                            0.7
google                           2.0.3
google-api-core                  2.11.1
google-api-python-client         2.84.0
google-auth                      2.17.3
google-auth-httplib2             0.1.0
google-auth-oauthlib             1.0.0
google-cloud-bigquery            3.10.0
google-cloud-bigquery-connection 1.12.1
google-cloud-bigquery-storage    2.22.0
google-cloud-core                2.3.3
google-cloud-datastore           2.15.2
google-cloud-firestore           2.11.1
google-cloud-functions           1.13.1
google-cloud-language            2.9.1
google-cloud-storage             2.8.0
google-cloud-translate           3.11.2
google-colab                     1.0.0
google-crc32c                    1.5.0
google-pasta                     0.2.0
google-resumable-media           2.5.0
googleapis-common-protos         1.59.1
googledrivedownloader            0.4
graphviz                         0.20.1
greenlet                         2.0.2
grpc-google-iam-v1               0.12.6
grpcio                           1.56.0
grpcio-status                    1.48.2
gspread                          3.4.2
gspread-dataframe                3.3.1
gym                              0.25.2
gym-notices                      0.0.8
h5netcdf                         1.2.0
h5py                             3.8.0
holidays                         0.28
holoviews                        1.15.4
html5lib                         1.1
httpimport                       1.3.0
httplib2                         0.21.0
humanize                         4.6.0
hyperopt                         0.2.7
idna                             3.4
imageio                          2.25.1
imageio-ffmpeg                   0.4.8
imagesize                        1.4.1
imbalanced-learn                 0.10.1
imgaug                           0.4.0
importlib-resources              6.0.0
imutils                          0.5.4
inflect                          6.0.5
iniconfig                        2.0.0
intel-openmp                     2023.1.0
ipykernel                        5.5.6
ipython                          7.34.0
ipython-genutils                 0.2.0
ipython-sql                      0.4.1
ipywidgets                       7.7.1
itsdangerous                     2.1.2
jax                              0.4.13
jaxlib                           0.4.13+cuda11.cudnn86
jieba                            0.42.1
Jinja2                           3.1.2
joblib                           1.3.1
jsonpickle                       3.0.1
jsonschema                       4.3.3
jupyter-client                   6.1.12
jupyter-console                  6.1.0
jupyter_core                     5.3.1
jupyter-server                   1.24.0
jupyterlab-pygments              0.2.2
jupyterlab-widgets               3.0.8
kaggle                           1.5.15
keras                            2.12.0
kiwisolver                       1.4.4
langcodes                        3.3.0
lazy_loader                      0.3
libclang                         16.0.0
librosa                          0.10.0.post2
lightgbm                         3.3.5
lit                              16.0.6
llvmlite                         0.39.1
locket                           1.0.0
logical-unification              0.4.6
LunarCalendar                    0.0.9
lxml                             4.9.3
Markdown                         3.4.3
markdown-it-py                   3.0.0
MarkupSafe                       2.1.3
matplotlib                       3.7.1
matplotlib-inline                0.1.6
matplotlib-venn                  0.11.9
mdurl                            0.1.2
miniKanren                       1.0.3
missingno                        0.5.2
mistune                          0.8.4
mizani                           0.8.1
mkl                              2019.0
ml-dtypes                        0.2.0
mlxtend                          0.22.0
more-itertools                   9.1.0
moviepy                          1.0.3
mpmath                           1.3.0
msgpack                          1.0.5
multidict                        6.0.4
multipledispatch                 1.0.0
multitasking                     0.0.11
murmurhash                       1.0.9
music21                          8.1.0
natsort                          8.3.1
nbclient                         0.8.0
nbconvert                        6.5.4
nbformat                         5.9.1
nest-asyncio                     1.5.6
networkx                         3.1
nibabel                          3.0.2
nltk                             3.8.1
notebook                         6.4.8
numba                            0.56.4
numexpr                          2.8.4
numpy                            1.22.4
oauth2client                     4.1.3
oauthlib                         3.2.2
opencv-contrib-python            4.7.0.72
opencv-python                    4.7.0.72
opencv-python-headless           4.8.0.74
openpyxl                         3.0.10
opt-einsum                       3.3.0
optax                            0.1.5
orbax-checkpoint                 0.2.7
osqp                             0.6.2.post8
packaging                        23.1
palettable                       3.3.3
pandas                           1.5.3
pandas-datareader                0.10.0
pandas-gbq                       0.17.9
pandocfilters                    1.5.0
panel                            0.14.4
param                            1.13.0
parso                            0.8.3
partd                            1.4.0
pathlib                          1.0.1
pathy                            0.10.2
patsy                            0.5.3
pexpect                          4.8.0
pickleshare                      0.7.5
Pillow                           8.4.0
pip                              23.1.2
pip-tools                        6.13.0
platformdirs                     3.8.1
plotly                           5.13.1
plotnine                         0.10.1
pluggy                           1.2.0
polars                           0.17.3
pooch                            1.6.0
portpicker                       1.5.2
prefetch-generator               1.0.3
preshed                          3.0.8
prettytable                      0.7.2
proglog                          0.1.10
progressbar2                     4.2.0
prometheus-client                0.17.1
promise                          2.3
prompt-toolkit                   3.0.39
prophet                          1.1.4
proto-plus                       1.22.3
protobuf                         3.20.3
psutil                           5.9.5
psycopg2                         2.9.6
ptyprocess                       0.7.0
py-cpuinfo                       9.0.0
py4j                             0.10.9.7
pyarrow                          9.0.0
pyasn1                           0.5.0
pyasn1-modules                   0.3.0
pycocotools                      2.0.6
pycparser                        2.21
pyct                             0.5.0
pydantic                         1.10.11
pydata-google-auth               1.8.1
pydot                            1.4.2
pydot-ng                         2.0.0
pydotplus                        2.0.2
PyDrive                          1.3.1
pyerfa                           2.0.0.3
pygame                           2.5.0
Pygments                         2.14.0
PyGObject                        3.36.0
pymc                             5.1.2
PyMeeus                          0.5.12
pymystem3                        0.2.0
PyOpenGL                         3.1.7
pyparsing                        3.1.0
pyproj                           3.6.0
pyproject_hooks                  1.0.0
pyrsistent                       0.19.3
PySocks                          1.7.1
pytensor                         2.10.1
pytest                           7.2.2
python-apt                       0.0.0
python-dateutil                  2.8.2
python-louvain                   0.16
python-slugify                   8.0.1
python-utils                     3.7.0
pytz                             2022.7.1
pyviz-comms                      2.3.2
PyWavelets                       1.4.1
PyYAML                           6.0
pyzmq                            23.2.1
qdldl                            0.1.7.post0
qudida                           0.0.4
regex                            2022.10.31
requests                         2.27.1
requests-oauthlib                1.3.1
requests-unixsocket              0.2.0
requirements-parser              0.5.0
rich                             13.4.2
rpy2                             3.5.5
rsa                              4.9
scikit-image                     0.19.3
scikit-learn                     1.2.2
scipy                            1.10.1
scs                              3.2.3
seaborn                          0.12.2
Send2Trash                       1.8.2
setuptools                       67.7.2
shapely                          2.0.1
six                              1.16.0
sklearn-pandas                   2.2.0
smart-open                       6.3.0
sniffio                          1.3.0
snowballstemmer                  2.2.0
sortedcontainers                 2.4.0
soundfile                        0.12.1
soupsieve                        2.4.1
soxr                             0.3.5
spacy                            3.5.4
spacy-legacy                     3.0.12
spacy-loggers                    1.0.4
Sphinx                           3.5.4
sphinxcontrib-applehelp          1.0.4
sphinxcontrib-devhelp            1.0.2
sphinxcontrib-htmlhelp           2.0.1
sphinxcontrib-jsmath             1.0.1
sphinxcontrib-qthelp             1.0.3
sphinxcontrib-serializinghtml    1.1.5
SQLAlchemy                       2.0.18
sqlparse                         0.4.4
srsly                            2.4.6
statsmodels                      0.13.5
sympy                            1.11.1
tables                           3.8.0
tabulate                         0.8.10
tblib                            2.0.0
tenacity                         8.2.2
tensorboard                      2.12.3
tensorboard-data-server          0.7.1
tensorflow                       2.12.0
tensorflow-datasets              4.9.2
tensorflow-estimator             2.12.0
tensorflow-gcs-config            2.12.0
tensorflow-hub                   0.13.0
tensorflow-io-gcs-filesystem     0.32.0
tensorflow-metadata              1.13.1
tensorflow-probability           0.20.1
tensorstore                      0.1.40
termcolor                        2.3.0
terminado                        0.17.1
text-unidecode                   1.3
textblob                         0.17.1
tf-slim                          1.1.0
thinc                            8.1.10
threadpoolctl                    3.1.0
tifffile                         2023.7.10
tinycss2                         1.2.1
toml                             0.10.2
tomli                            2.0.1
toolz                            0.12.0
torch                            2.0.1+cu118
torchaudio                       2.0.2+cu118
torchdata                        0.6.1
torchsummary                     1.5.1
torchtext                        0.15.2
torchvision                      0.15.2+cu118
tornado                          6.3.1
tqdm                             4.65.0
traitlets                        5.7.1
triton                           2.0.0
tweepy                           4.13.0
typer                            0.9.0
types-setuptools                 68.0.0.1
typing_extensions                4.7.1
tzlocal                          5.0.1
uritemplate                      4.1.1
urllib3                          1.26.16
vega-datasets                    0.9.0
wasabi                           1.1.2
wcwidth                          0.2.6
webcolors                        1.13
webencodings                     0.5.1
websocket-client                 1.6.1
Werkzeug                         2.3.6
wheel                            0.40.0
widgetsnbextension               3.6.4
wordcloud                        1.8.2.2
wrapt                            1.14.1
xarray                           2022.12.0
xarray-einstats                  0.6.0
xgboost                          1.7.6
xlrd                             2.0.1
yarl                             1.9.2
yellowbrick                      1.5
yfinance                         0.2.22
zict                             3.0.0
zipp                             3.16.0

In [3]:
import pandas as pd

In [28]:
pd.read_csv("https://raw.githubusercontent.com/sagnikghoshcr7/Bank-Customer-Churn-Prediction/master/Churn_Modelling.csv")

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [7]:
df= pd.read_csv("https://raw.githubusercontent.com/sagnikghoshcr7/Bank-Customer-Churn-Prediction/master/Churn_Modelling.csv")

In [8]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [9]:
df.drop(columns=['RowNumber', 'CustomerId', 'Surname'],inplace = True)

In [10]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
df["Geography"].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [12]:
df["Gender"].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [13]:
pd.get_dummies(df,columns=["Geography", "Gender"],drop_first=True)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0,0

In [14]:
df =pd.get_dummies(df,columns=["Geography", "Gender"],drop_first=True)

In [16]:
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,0

In [19]:
df.drop(["Exited"],axis = 1)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,1,0
2,502,42,8,159660.80,3,1,0,113931.57,0,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,0,0,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,0,0

In [20]:
X = df.drop(["Exited"],axis = 1)

In [22]:
y = df["Exited"]

In [23]:
import tensorflow
from tensorflow import keras

In [26]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [27]:
len(X.columns)

11

In [31]:
model = Sequential()
model.add(Dense(9,activation="sigmoid", input_dim=11))#input layer, 9 is for hidden layer
model.add(Dense(11,activation="sigmoid"))#hidden layer
model.add(Dense(1,activation="sigmoid"))#output layer

In [32]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 9)                 108

 dense_4 (Dense)             (None, 11)                110

 dense_5 (Dense)             (None, 1)                 12

=================================================================
Total params: 230
Trainable params: 230
Non-trainable params: 0
_________________________________________________________________

In [33]:
model = Sequential()
model.add(Dense(11,activation="sigmoid", input_dim=11))#input layer, 9 is for hidden layer
model.add(Dense(11,activation="sigmoid"))#hidden layer
model.add(Dense(1,activation="sigmoid"))#output layer

In [34]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_6 (Dense)             (None, 11)                132

 dense_7 (Dense)             (None, 11)                132

 dense_8 (Dense)             (None, 1)                 12

=================================================================
Total params: 276
Trainable params: 276
Non-trainable params: 0
_________________________________________________________________

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state = 0)

In [39]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)
X_test_scale = scaler.transform(X_test)

In [41]:
model.compile(optimizer="Adam", loss = "binary_crossentropy",metrics= ["accuracy"])

In [42]:
model.fit(X_train_scale,y_train,batch_size = 50,epochs=10,verbose=1)

Epoch 1/10
160/160 [==============================] - 6s 4ms/step - loss: 0.5327 - accuracy: 0.7960
Epoch 2/10
160/160 [==============================] - 1s 4ms/step - loss: 0.4860 - accuracy: 0.7960
Epoch 3/10
160/160 [==============================] - 1s 4ms/step - loss: 0.4725 - accuracy: 0.7960
Epoch 4/10
160/160 [==============================] - 0s 3ms/step - loss: 0.4601 - accuracy: 0.7960
Epoch 5/10
160/160 [==============================] - 0s 3ms/step - loss: 0.4493 - accuracy: 0.7960
Epoch 6/10
160/160 [==============================] - 0s 3ms/step - loss: 0.4409 - accuracy: 0.7961
Epoch 7/10
160/160 [==============================] - 0s 3ms/step - loss: 0.4351 - accuracy: 0.8031
Epoch 8/10
160/160 [==============================] - 0s 3ms/step - loss: 0.4311 - accuracy: 0.8102
Epoch 9/10
160/160 [==============================] - 0s 3ms/step - loss: 0.4287 - accuracy: 0.8106
Epoch 10/10
160/160 [==============================] - 0s 3ms/step - loss: 0.4267 - accuracy: 0.8119

In [43]:
model.predict(X_test)

63/63 [==============================] - 0s 1ms/step

array([[0.42062098],
       [0.42062098],
       [0.42062098],
       ...,
       [0.42062098],
       [0.50091475],
       [0.42062098]], dtype=float32)

In [47]:
y_pred=model.predict(X_test_scale)

63/63 [==============================] - 0s 2ms/step

In [48]:
y_pred

array([[0.22017288],
       [0.37316847],
       [0.14680998],
       ...,
       [0.15731026],
       [0.11692332],
       [0.197455  ]], dtype=float32)

In [50]:
y_pred=y_pred.argmax(axis=-1)

In [51]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7975